version: '3'

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: abi
      MYSQL_ROOT_PASSWORD: abi
    volumes:
      - mysql_data:/var/lib/mysql
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /code  # Match this with the Dockerfile WORKDIR
    command: ["/bin/bash", "-c", "./a.sh && python manage.py runserver 0.0.0.0:8000"]

    volumes:
      - .:/code 
    ports:
     - "8000:8000"
    environment:
      - DB_NAME=abi
      - DB_USER=abi
      - DB_PASSWORD=abi
      - DB_HOST=mysql
      - DB_PORT=3306
    
    depends_on:
      - mysql
