version: '3'

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: abi
      MYSQL_ROOT_PASSWORD: abi
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  # Add healthcheck to ensure service readiness
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5    
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /code  # Match this with the Dockerfile WORKDIR
    command: ["bash", "a.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]

    volumes:
      - .:/code  # Mounts current directory to /code for consistency
    ports:
     - "8000:8000"
    environment:
      - DB_NAME=abi
      - DB_USER=abi
      - DB_PASSWORD=abi
      - DB_HOST=mysql
      - DB_PORT=3306
    
    depends_on:
      - mysql
